//! Wire-format parsing, and the one place that knows more than one version
//! exists.
//!
//! # Dispatch contract
//!
//! Opening a dictionary parses the bounded common header exactly once,
//! resolves exactly one [`WireVersion`] from it, and then enters exactly one
//! grammar:
//!
//! ```text
//! common header -> WireVersion -> v1::parse_layout | v2::parse_layout
//!                              -> ValidatedLayout  -> shared core
//! ```
//!
//! [`open_layout`] contains the only `match` on [`WireVersion`] in the crate.
//! A grammar that fails is never retried under the other grammar, and no code
//! path rewrites one version's bytes into another's shape.
//!
//! `format::v1` and `format::v2` cannot see each other, and cannot see the
//! core or the MDX/MDD facades. Everything they share lives in [`common`], and
//! everything they produce is a
//! [`ValidatedLayout`](common::descriptors::ValidatedLayout).

pub(crate) mod common;
mod v1;
mod v2;

use std::sync::Arc;

use crate::error::{Error, Result};
use crate::limits::MemoryBudget;
use crate::types::{ContainerKind, OpenOptions};

use self::common::descriptors::ValidatedLayout;
use self::common::header::{HeaderSection, parse_header};
use self::common::source::FileSource;

pub(crate) use self::common::encoding::TextEncoding;

/// The major wire version a file declares.
///
/// This enum exists only inside this module. Resolving it and matching on it
/// both happen once, during open; nothing downstream can name it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum WireVersion {
    V1,
    V2,
}

/// Everything a grammar needs to parse a file, so both `parse_layout`
/// signatures stay identical and reviewable side by side.
pub(crate) struct LayoutRequest<'a> {
    pub(crate) source: &'a FileSource,
    pub(crate) header_section: HeaderSection,
    pub(crate) kind: ContainerKind,
    pub(crate) options: &'a OpenOptions,
    pub(crate) memory: &'a Arc<MemoryBudget>,
}

/// Parses one dictionary file into a version-neutral validated layout.
///
/// # Errors
///
/// Returns an error if the common header is malformed or exceeds a limit, the
/// declared version is unsupported or ambiguous, or the selected grammar
/// rejects the file's geometry.
pub(crate) fn open_layout(
    source: &FileSource,
    kind: ContainerKind,
    options: &OpenOptions,
    memory: &Arc<MemoryBudget>,
) -> Result<ValidatedLayout> {
    let header_section = parse_header(source, kind, &options.limits, memory)?;
    let generated_major = declared_major_version(
        header_section.header.generated_by_engine_version(),
        "malformed GeneratedByEngineVersion",
    )?;
    // GeneratedByEngineVersion remains the dispatch authority. Resolve it
    // before inspecting RequiredEngineVersion so an unsupported generated
    // grammar is reported consistently even when unrelated compatibility
    // metadata is malformed.
    let version = resolve_wire_version(generated_major)?;
    let required_major = declared_major_version(
        header_section.header.required_engine_version(),
        "malformed RequiredEngineVersion",
    )?;
    validate_version_relationship(generated_major, required_major)?;
    let request = LayoutRequest {
        source,
        header_section,
        kind,
        options,
        memory,
    };

    // The only version match in the crate. Each arm is entered at most once
    // per open, and a failure inside an arm propagates instead of falling
    // through to the other grammar.
    let layout = match version {
        WireVersion::V1 => v1::parse_layout(request),
        WireVersion::V2 => v2::parse_layout(request),
    }?;

    layout.verify()?;
    Ok(layout)
}

/// Extracts the declared major component of an engine-version attribute.
///
/// Every component must be a non-empty ASCII decimal integer. Only the major
/// component affects dispatch, but validating the complete spelling here keeps
/// malformed compatibility metadata out of application adapters.
fn declared_major_version(version: &str, malformed: &'static str) -> Result<u32> {
    let mut components = version.split('.');
    let major = components
        .next()
        .filter(|component| {
            !component.is_empty() && component.bytes().all(|byte| byte.is_ascii_digit())
        })
        .and_then(|component| component.parse::<u32>().ok())
        .ok_or(Error::InvalidFormat(malformed))?;
    if components.any(|component| {
        component.is_empty() || !component.bytes().all(|byte| byte.is_ascii_digit())
    }) {
        return Err(Error::InvalidFormat(malformed));
    }
    Ok(major)
}

/// Validates compatibility metadata without changing the dispatch authority.
///
/// A version 2 producer may require a version 1 reader, but a file declaring
/// that it was generated by version 1 cannot coherently require version 2.
/// Future requirements are refused before any version-specific bytes are read.
fn validate_version_relationship(generated_major: u32, required_major: u32) -> Result<()> {
    if required_major == 0 {
        return Err(Error::InvalidFormat(
            "RequiredEngineVersion must have a non-zero major version",
        ));
    }
    if required_major > 2 {
        return Err(Error::Unsupported(
            "required MDict engine major version other than 1 or 2",
        ));
    }
    if generated_major == 1 && required_major != 1 {
        return Err(Error::InvalidFormat(
            "GeneratedByEngineVersion 1 conflicts with RequiredEngineVersion",
        ));
    }
    Ok(())
}

/// Maps a declared major version onto an implemented grammar.
///
/// `GeneratedByEngineVersion` is the authority, matching the shipped `0.1.0`
/// behavior. `RequiredEngineVersion` is validated separately for compatibility
/// but never selects the grammar, so an unrelated requirement cannot change the
/// wire-format dispatch.
fn resolve_wire_version(declared_major: u32) -> Result<WireVersion> {
    match declared_major {
        1 => Ok(WireVersion::V1),
        2 => Ok(WireVersion::V2),
        _ => Err(Error::Unsupported(
            "MDict format major version other than 1 or 2",
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_each_implemented_major_version() {
        assert_eq!(
            resolve_wire_version(declared_major_version("1.2", "malformed").unwrap()).unwrap(),
            WireVersion::V1
        );
        assert_eq!(
            resolve_wire_version(declared_major_version("2.0", "malformed").unwrap()).unwrap(),
            WireVersion::V2
        );
    }

    #[test]
    fn accepts_a_bare_major_component() {
        assert_eq!(declared_major_version("1", "malformed").unwrap(), 1);
        assert_eq!(declared_major_version("2", "malformed").unwrap(), 2);
    }

    #[test]
    fn rejects_unsupported_and_unparsable_versions() {
        for declared in ["", "x.y", "two", " 2.0", "-1.0", "1x.2", "2.", ".2"] {
            let error = declared_major_version(declared, "malformed").unwrap_err();
            assert!(matches!(error, Error::InvalidFormat("malformed")));
        }
        for declared in ["0.9", "3.0"] {
            let major = declared_major_version(declared, "malformed").unwrap();
            assert!(matches!(
                resolve_wire_version(major),
                Err(Error::Unsupported(_))
            ));
        }
    }

    #[test]
    fn validates_minor_and_trailing_components_without_using_them_for_dispatch() {
        assert_eq!(declared_major_version("1.2.3.4", "malformed").unwrap(), 1);
        assert!(declared_major_version("2.0-beta", "malformed").is_err());
    }

    #[test]
    fn validates_required_version_without_changing_generated_dispatch_authority() {
        assert!(validate_version_relationship(2, 1).is_ok());
        assert!(matches!(
            validate_version_relationship(1, 2),
            Err(Error::InvalidFormat(_))
        ));
        assert!(matches!(
            validate_version_relationship(2, 3),
            Err(Error::Unsupported(_))
        ));
    }
}
